CUISINES = [
    "Soul Food",
    "South American",
    "South Asian",
    "Southern",
    "Southwestern",
    "Spanish",
    "Tex Mex",
    "Thai",
    "Turkish",
    "Venezuelan",
    "Vietnamese",
    "West African",
    "African",
    "American",
    "Asian",
    "Australian",
    "Austrian",
    "Belgian",
    "Brazilian",
    "British",
    "Cajun",
    "Caribbean",
    "Central ",
    "Chinese",
    "Creole",
    "Cuban",
    "Eastern",
    "Filipino",
    "French",
    "German",
    "Greek",
    "Indian",
    "Indonesian",
    "Iranian",
    "Irish",
    "Italian",
    "Italian ",
    "Jamaican",
    "Japanese",
    "Jewish",
    "Korean",
    "Latin American",
    "Lebanese",
    "Malaysian",
    "Mediterranean",
    "Mexican",
    "Middle Eastern",
    "Moroccan",
    "New England",
    "Nordic",
    "Pakistani",
    "Portuguese",
    "Russian",
]

OCCASIONS = [
  "School Lunch",
  "Snack",
  "Spring",
  "St. Patrick's Day",
  "Summer",
  "Super Bowl",
  "Thanksgiving",
  "Thanksgiving Leftover",
  "Valentine's Day",
  "Weekday",
  "Weeknight",
  "Appetizer",
  "Barbecues",
  "Birthday",
  "Breakfast",
  "Brunch",
  "Budget",
  "Christmas",
  "Christmas Cookie",
  "Date Night",
  "Dessert",
  "Dinner",
  "Diwali",
  "Easter",
  "Fall",
  "Father's Day",
  "For One",
  "For Two",
  "Fourth Of July",
  "Halloween",
  "Hanukkah",
  "Kentucky Derby",
  "Kwanzaa",
  "Labor Day",
  "Lunar New Year",
  "Lunch",
  "Main Course",
  "Make Ahead",
  "Mardi Gras",
  "Memorial Day",
  "Mother's Day",
  "New Year's Day",
  "Nowruz",
  "Party",
  "Passover",
  "Picnic",
  "Plan Ahead",
  "Quick",
  "Ramadan",
  "Rosh Hashana",
]

DIETS = [
  "Vegan",
  "Vegetarian",
  "Dairy Free",
  "Gluten Free",
  "Halal",
  "Healthy",
  "High Fiber",
  "High Protein",
  "Kid Friendly",
  "Kosher",
  "Low Calorie",
  "Low Carb",
  "Low Fat",
  "Low Sodium",
  "Low Sugar",
  "Nut Free",
  "Raw",
]