CUISINES = [
    "Soul Food",
    "South American",
    "South Asian",
    "Southern",
    "Southwestern",
    "Spanish",
    "Tex Mex",
    "Thai",
    "Turkish",
    "Venezuelan",
    "Vietnamese",
    "West African",
    "African",
    "American",
    "Asian",
    "Australian",
    "Austrian",
    "Belgian",
    "Brazilian",
    "British",
    "Cajun",
    "Caribbean",
    "Central ",
    "Chinese",
    "Creole",
    "Cuban",
    "Eastern",
    "Filipino",
    "French",
    "German",
    "Greek",
    "Indian",
    "Indonesian",
    "Iranian",
    "Irish",
    "Italian",
    "Italian ",
    "Jamaican",
    "Japanese",
    "Jewish",
    "Korean",
    "Latin American",
    "Lebanese",
    "Malaysian",
    "Mediterranean",
    "Mexican",
    "Middle Eastern",
    "Moroccan",
    "New England",
    "Nordic",
    "Pakistani",
    "Portuguese",
    "Russian",
]

OCCASIONS = [
    "School Lunch",
    "Snack",
    "Spring",
    "St. Patrick's Day",
    "Summer",
    "Super Bowl",
    "Thanksgiving",
    "Thanksgiving Leftover",
    "Valentine's Day",
    "Weekday",
    "Weeknight",
    "Appetizer",
    "Barbecues",
    "Birthday",
    "Breakfast",
    "Brunch",
    "Budget",
    "Christmas",
    "Christmas Cookie",
    "Date Night",
    "Dessert",
    "Dinner",
    "Diwali",
    "Easter",
    "Fall",
    "Father's Day",
    "For One",
    "For Two",
    "Fourth Of July",
    "Halloween",
    "Hanukkah",
    "Kentucky Derby",
    "Kwanzaa",
    "Labor Day",
    "Lunar New Year",
    "Lunch",
    "Main Course",
    "Make Ahead",
    "Mardi Gras",
    "Memorial Day",
    "Mother's Day",
    "New Year's Day",
    "Nowruz",
    "Party",
    "Passover",
    "Picnic",
    "Plan Ahead",
    "Quick",
    "Ramadan",
    "Rosh Hashana",
]

DIETS = [
    "Vegan",
    "Vegetarian",
    "Dairy Free",
    "Gluten Free",
    "Halal",
    "Healthy",
    "High Fiber",
    "High Protein",
    "Kid Friendly",
    "Kosher",
    "Low Calorie",
    "Low Carb",
    "Low Fat",
    "Low Sodium",
    "Low Sugar",
    "Nut Free",
    "Raw",
]

EQUIPMENT = [
    "Sheet Pan"
    "Skillet"
    "Slow Cooker"
    "Stovetop"
    "Air Fryer"
    "Barbecue"
    "Cast Iron"
    "Dutch Oven"
    "Food Processor"
    "Freezer Friendly"
]

KEY_INGREDIENTS = [
    "Anchovy",
    "Andouille Sausage",
    "Apple",
    "Apple Cider",
    "Applesauce",
    "Arborio Rice",
    "Arctic Char",
    "Artichoke",
    "Artichoke Heart",
    "Arugula",
    "Asparagus",
    "Avocado",
    "Baby Carrot",
    "Bacon",
    "Balsamic Vinegar",
    "Banana",
    "Basil",
    "Bay Leaves",
    "Bay Scallop",
    "Beans",
    "Beef",
    "Beef Broth",
    "Beer",
    "Beet",
    "Bell Pepper",
    "Black Bean",
    "Black Eyed Pea",
    "Black Olives",
    "Black Truffle",
    "Blueberry",
    "Bok Choy",
    "Brie",
    "Brisket",
    "Broccoli",
    "Broccoli Rabe",
    "Broccolini",
    "Brown Rice",
    "Brussels Sprout",
    "Butter",
    "Butter Lettuce",
    "Butternut Squash",
    "Cabbage",
    "Canned Tuna",
    "Cannellini Bean",
    "Cantaloupe",
    "Caper",
    "Carrot",
    "Cashew",
    "Catfish",
    "Cauliflower",
    "Caviar",
    "Celery",
    "Chanterelle Mushroom",
    "Cheddar",
    "Cheese",
    "Cherry",
    "Cherry Tomato",
    "Chia Seed",
    "Chicken",
    "Chicken Breast",
    "Chicken Broth",
    "Chicken Wing",
    "Chickpea",
    "Chive",
    "Chocolate Chip",
    "Chorizo",
    "Cilantro",
    "Cinnamon",
    "Cinnamon Stick",
    "Citrus",
    "Clam",
    "Coconut Cream",
    "Coconut Flake",
    "Coconut Milk",
    "Cod",
    "Coffee",
    "Collard Green",
    "Corn",
    "Corn On The Cob",
    "Cornbread",
    "Cornish Hen",
    "Cottage Cheese",
    "Couscous",
    "Crab",
    "Cream",
    "Cream Cheese",
    "Creme Fraiche",
    "Cucumber",
    "Daikon",
    "Dill",
    "Duck",
    "Duck Breast",
    "Duck Fat",
    "Duck Leg",
    "Edamame",
    "Egg",
    "Egg White",
    "Egg Yolk",
    "Eggplant",
    "Endive",
    "Extra Virgin Olive Oil",
    "Farro",
    "Feta",
    "Fettuccine",
    "Fish",
    "Fruit",
    "Garlic",
    "Ginger",
    "Grape",
    "Grape Tomato",
    "Grapefruit",
    "Greek Yogurt",
    "Green Olives",
    "Ground Beef",
    "Ground Meat",
    "Guacamole",
    "Halibut",
    "Ham",
    "Haricot Vert",
    "Harissa",
    "Hazelnut",
    "Hearts Of Palm",
    "Heirloom Tomato",
    "Herb",
    "Honey",
    "Hot Dog",
    "Hummus",
    "Iceberg Lettuce",
    "Italian Bread",
    "Italian Parsley",
    "Italian Sausage",
    "Jalapeno",
    "Kalamata Olive",
    "Kale",
    "Lamb",
    "Lamb Chop",
    "Leek",
    "Lemon",
    "Lettuce",
    "Lime",
    "Lime Juice",
    "Linguine",
    "Littleneck Clam",
    "Lobster",
    "Mackerel",
    "Mango",
    "Maple Syrup",
    "Matcha",
    "Mayonnaise",
    "Melon",
    "Mesclun",
    "Milk",
    "Mint",
    "Mirin",
    "Miso",
    "Miso Paste",
    "Mozzarella",
    "Mushroom",
    "Mustard Green",
    "Napa Cabbage",
    "Noodles",
    "Octopus",
    "Okra",
    "Olive",
    "Olive Oil",
    "Onion",
    "Orange",
    "Oyster",
    "Oyster Mushroom",
    "Pancetta",
    "Parmesan",
    "Parsley",
    "Parsnip",
    "Pasta",
    "Pea",
    "Pea Shoot",
    "Peach",
    "Peanut",
    "Peanut Butter",
    "Pear",
    "Pecan",
    "Pecan Pie",
    "Pecorino",
    "Penne",
    "Pepper",
    "Pine Nut",
    "Pineapple",
    "Pinto Bean",
    "Pita",
    "Pomegranate",
    "Pork",
    "Pork Belly",
    "Pork Tenderloin",
    "Portobello",
    "Potato",
    "Prosciutto",
    "Pumpkin",
    "Quinoa",
    "Red Onion",
    "Rice",
    "Ricotta",
    "Risotto",
    "Romaine",
    "Rosemary",
    "Salmon",
    "Sausage",
    "Sausages",
    "Scallion",
    "Scallop",
    "Sea Bass",
    "Short Rib",
    "Shrimp",
    "Snow Pea",
    "Soba Noodle",
    "Soda",
    "Sour Cream",
    "Spaghetti",
    "Spaghetti Squash",
    "Spinach",
    "Squash",
    "Steak",
    "Strawberry",
    "Sun Dried Tomato",
    "Sunchoke",
    "Sweet Potato",
    "Swiss Chard",
    "Swordfish",
    "Thyme",
    "Tofu",
    "Tomatillo",
    "Tomato",
    "Tomato Paste",
    "Tomato Sauce",
    "Tuna",
    "Turkey",
    "Veal",
    "Vinegar",
    "Watermelon",
    "Wine",
    "Yellow Onion",
    "Yogurt",
    "Zucchini",
]


DRINK_INGREDIENTS = [
    "Campari",
    "Candied Ginger",
    "Aperol",
    "Apple Brandy",
    "Apple Juice",
    "Basil",
    "Beer",
    "Carrot Juice",
    "Club Soda",
    "Champagne",
    "Cider",
    "Cognac",
    "Cointreau",
    "Cynar",
    "Dry Vermouth",
    "Gin",
    "Ginger Ale",
    "Ginger Beer",
    "Grand Marnier",
    "Grapefruit Juice",
    "Grappa",
    "Irish Whiskey",
    "Lime",
    "Lime Juice",
    "Mezcal",
    "Pineapple Juice",
    "Port",
    "Prosecco",
    "Ruby Port",
    "Rum",
    "Rye",
    "Rye Whiskey",
    "Scotch",
    "Sparkling Wine",
    "Tequila",
    "Tonic Water",
    "Triple Sec",
    "Vermouth",
    "Vodka",
    "Whiskey",
    "White Wine",
]
